# Generated by Django 6.1.1 on 2026-09-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('family', 'خانواده'), ('work', 'کار'), ('friends', 'دوستان'), ('other', 'سایر')], default='other', max_length=20),
        ),
    ]
