# Generated by Django 6.1.1 on 2026-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_contact_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('customer', 'مشتری\u200cها'), ('thread_seller', 'نخ فروش\u200cها'), ('parts_seller', 'قطعه فروش\u200cها'), ('oil_seller', 'روغن فروش\u200cها'), ('dyeing', 'رنگرزی'), ('spinning', 'ریسندگی'), ('knitting', 'بافندگی')], default='customer', max_length=20),
        ),
    ]
